const mongoose = require('mongoose');

/**
 * SOLTR — server/models/Wishlist.js
 *
 * Keyed to visitorId — the same anonymous, persistent-per-browser ID
 * already generated by getOrCreateVisitorId() in script.js/product.js
 * for the visitor-analytics feature (server/models/Visitor.js).
 *
 * NOT keyed to an admin JWT: this project has no customer account
 * system, only a single admin login for the dashboard. Gating a
 * storefront wishlist behind admin credentials would be broken for
 * real customers, so this reuses the same anonymous-visitor identity
 * the cart and visit-tracking already rely on instead.
 *
 * productId is a real ref (not a snapshot) — unlike Order.items, a
 * wishlist entry should always reflect the product's CURRENT price/
 * stock/name, since it's an ongoing "things I might buy" list, not a
 * record of a completed transaction.
 */
const wishlistSchema = new mongoose.Schema(
  {
    visitorId: { type: String, required: true, trim: true },
    productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
  },
  { timestamps: true }
);

/* One entry per (visitor, product) — prevents duplicate wishlist rows at the DB level */
wishlistSchema.index({ visitorId: 1, productId: 1 }, { unique: true });

module.exports = mongoose.model('Wishlist', wishlistSchema);
